# Generated by Django 5.1.1 on 2024-10-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="added_by",
            field=models.CharField(
                choices=[("scraper", "Lisboa Pulse"), ("user", "User")], max_length=50
            ),
        ),
    ]
