# Generated by Django 5.1.2 on 2024-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.CharField(max_length=255),
        ),
    ]
