# Generated by Django 5.1.2 on 2024-10-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="added_by",
            field=models.CharField(
                blank=True,
                choices=[("scraper", "Lisboa Pulse"), ("user", "User")],
                max_length=50,
                null=True,
            ),
        ),
    ]
