# Generated by Django 5.1.2 on 2024-10-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="added_by",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
