# TODO: add this hook to all microservices, add directories to args

repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language: system  # using system so it will run when inside microservices
        entry: poetry run black .
        pass_filenames: false  # checking whole project

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        language: system
        entry: poetry run isort .
        pass_filenames: false
        cwd: event_management_service

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        language: system
        entry: poetry run flake8
        pass_filenames: false
        cwd: event_management_service
